# Generated by Django 3.0 on 2021-02-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_subject', models.CharField(choices=[('01', 'math'), ('02', 'sci'), ('03', 'art'), ('04', 'eng'), ('05', 'physics'), ('06', 'bio')], default='01', max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
